### ISSUE TITLE
owp/file-to-string(nil) instead of stringp

### ISSUE THREAD

**Issue by shackra** [tumashu/org-webpage#11]
For some reason I can't understand, making a full export using rclone as the sender will cause this error:

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  insert-file-contents(nil)
  owp/file-to-string(nil)
  owp/generate-and-run-uploader("/home/jorge/.emacs.d/owp-temp.d/El blog de Shackra/owp-uploader.sh" (rclone "rscf" "elblog.deshackra.com") "/home/jorge/.emacs.d/owp-temp.d/El blog de Shackra/export/" "/home/jorge/.emacs.d/owp-temp.d/El blog de Shackra/history/" "/home/jorge/.emacs.d/owp-temp.d/El blog de Shackra/publish/" nil)
  owp/do-publication()
  call-interactively(owp/do-publication record nil)
  command-execute(owp/do-publication record)
  helm-M-x(nil "owp/do-publication")
  call-interactively(helm-M-x nil nil)
  command-execute(helm-M-x)
```

Anything missing in that call to `owp/file-to-string`

**Comment by tumashu** [comment]
Please test the following form,

```
(owp/get-uploader-template "rclone.mustache")
```

**Comment by tumashu** [comment]
If return nil, you can upgrade org-webpage from melpa to version 20160812.409, then try again.

**Comment by elzorrorebelde** [comment]
It actually returned nil, I'm going to update and report back soon as possible!

El viernes 12 de agosto del 2016 a las 2312 horas, tumashu escribió:

> If return nil, you can upgrade org-webpage from melpa to version 20160812.409,
> then try again.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

## 

👋 Pax et bonum.
Jorge Araya Navarro
https://es.gravatar.com/shackra

**Comment by elzorrorebelde** [comment]
the last update fix this issue!

**Comment by tumashu** [comment]
now, org-webpage can find uploader template from “repo/uploaders ”,  user can develop their uploader template for a project

**Comment by elzorrorebelde** [comment]
That was actually one of my first assumptions before I ended hacking the project's code, ha! well, I'm glad to know that now that feature is a reality!
