### ISSUE TITLE
How to add regular pages?

### ISSUE THREAD

**Issue by stig** [tumashu/org-webpage#14]
In addition to index and about pages, is it possible to add other custom pages? I am trying to convert [my website](http://www.superloopy.io) to use this tool, but I want to preserve the links. Currently I have a "publications.html" page in the top level that keeps being incorporated in the post list rather than a separate top-level page. Am I doing something wrong?

**Comment by tumashu** [comment]
Do you mean add "publications" to nav bar?

**Comment by stig** [comment]
Yes, adding things to Nav bar I suppose is what I meant. But also removing as blog post.

**Comment by tumashu** [comment]
There are some methods:

method1:  mkdir <repos>/publications/ and put publications.org to it

method2:  edit publications.org 's header

```
    #+URI:         /publications/
```

method3:  custom owp/category-config-alist

```
(push '("publications"
        :show-meta nil
        :show-comment nil
        :uri-generator owp/generate-uri
        :uri-template "/publications/"
        :sort-by :date
        :category-index nil)
       owp/category-config-alist)

```

method4: custom theme and put your theme to <repo>/themes

**Comment by stig** [comment]
Thank you for all the answers! I think that answers my question.

**Comment by tumashu** [comment]
/themes/  means  "your repo dir"/themes/
