### ISSUE TITLE
Make nav float

### ISSUE THREAD

**Issue by thiefuniverse** [tumashu/org-webpage#16]
Hello,  I think if nav labels (blog,study,tags …)  are float with blog browsing, it will be comfortable.
This is really a nice tool, I will hack it when I 'm free.

**Comment by tumashu** [comment]
pull request is welcome

**Comment by tumashu** [comment]
你不是 blog-mini 的维护者吗？

**Comment by thiefuniverse** [comment]
是的，想从你这里吸取经验~
多多交流～

**Comment by tumashu** [comment]
org-webpage 和 EGO 都是源自 org-page， 三个之间的不同就是我们三个人理念上的一些分歧，但大部分代码都是类似的。

**Comment by tumashu** [comment]
org-page 主要是为了成为个人博客系统， 而 org-webpage 主要是为了维护微型主页，而 EGO 主要是为了 emacs-china 网站。

**Comment by thiefuniverse** [comment]
这样啊，我觉得org-page功能太多，太复杂，才想要自己弄一个简单点的．这是第一个包，开个头．
你的那个中文输入法看着很不错，回头我去试试. :laughing:

**Comment by tumashu** [comment]
org-webpage 和 org-page 最主要的区别有两点：
1. org-page 使用多个全局变量配置blog， org-webpage 使用一个 alist
2. org-page 集成 git， 而 org-webpage 使用 shell 脚本上传

**Comment by thiefuniverse** [comment]
我也用的全局变量配置，觉得alist集中一点，不知道alist可不可以用customize来配置.
blog-minimal还不支持自动上传，觉得git操作太多了,直接交给用户自己,反正有magit.

**Comment by tumashu** [comment]
customize 配置 alist 太痛苦，放弃吧

**Comment by tumashu** [comment]
反正个人感觉集成git就是和自己过不去，需要处理的边界问题太多了。。。。。

**Comment by thiefuniverse** [comment]
恩，好的．多谢指点！ :laughing:

**Comment by tumashu** [comment]
这个我先关闭了。
