### ISSUE TITLE
publications

### ISSUE THREAD

**Issue by arademaker** [tumashu/org-webpage#7]
Nice tool ! I am giving it a try to replace Jekyll in my website 

http://arademaker.github.io

Any idea about how to integrate it with https://github.com/jkitchin/org-ref? Currently with Jekyll-Scholar I am able to automatic produce one html file for each bibentry in my bibtex file. It would be nice to have some similar functionality. Let us share some ideas and maybe I can find time to contribute.

**Comment by tumashu** [comment]
org-ref seem focus on latex,  it is complicated but can work with org-webpage,  i use bibtex2html instead

**Comment by arademaker** [comment]
Thanks for your comment, can you share your workflow with bibtex2html?

**Comment by tumashu** [comment]
i use ox-bibtex , which is in org controb

**Comment by tumashu** [comment]
https://github.com/tumashu/emacs-helper/blob/master/eh-org-citation.el

**Comment by tumashu** [comment]
ebib is a good tool too

**Comment by arademaker** [comment]
Well, I am not sure if I really understood your suggestions. Hope to find time to dig more into it. Can you provide an example and more detailed description about how you use these tools?

**Comment by tumashu** [comment]
If you fimilar with org-ref, I don't think you should switch to other tools for org-ref is very actively maintained,  you can tell me the details of  feature requirement, if possible, a sample org sources is velcome.

**Comment by tumashu** [comment]
Seem no rep, closed.
